
services:
  petspace:
    image: wordpress:latest
    container_name: petspace-wordpress
    restart: always
    ports:
      - "4280:80"
    env_file: .env
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - sigma-net
    depends_on:
      - petspace-db

  petspace-db:
    image: mariadb:10.6
    container_name: petspace-db
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:4254:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sigma-net

volumes:
  db_data:

networks:
  sigma-net:
    external: true
